# Generated by Django 5.1.2 on 2024-12-12 16:20

import custom_app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='custommodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='name',
            field=custom_app.models.UpperCaseCharField(max_length=100, verbose_name='Текст'),
        ),
    ]
