# Generated by Django 5.1.2 on 2024-12-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0002_custommodel_created_at_custommodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_field', models.CharField(max_length=100, verbose_name="Пов'язане поле")),
                ('custom_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to='custom_app.custommodel')),
            ],
        ),
    ]
