# Generated by Django 5.1.2 on 2024-12-12 17:55

import custom_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0003_relatedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='phone_number',
            field=custom_app.models.PhoneNumberField(blank=True, max_length=15, null=True, verbose_name='Телефонний номер'),
        ),
    ]
