# Generated by Django 5.1.2 on 2024-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='HEX-код кольору'),
        ),
    ]
