# Generated by Django 5.1.4 on 2024-12-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публікації')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='session_app.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Оцінка')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='session_app.book', verbose_name='Книга')),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_title_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='review_rating_idx'),
        ),
    ]
